/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Visual;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ángel Torada
 */
public class AnyadirGasto extends javax.swing.JDialog {

    private final Gastos GastosFrame;

    /**
     * Constructor AnyadirGasto
     *
     * @param parent Instancia del parent
     * @param modal Determinará si es modal o no
     */
    public AnyadirGasto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Guardo la instancia del Frame padre en una variable
        GastosFrame = (Gastos) parent;
        //Oculto el panel de error
        jPanelErrorConcepto.setVisible(false);
        //Establezco la localización del dialog en el centro de la pantalla
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGasto = new javax.swing.JPanel();
        jLabelUnidadFamiliar = new javax.swing.JLabel();
        jCheckBoxUnidadFamiliar = new javax.swing.JCheckBox();
        jCheckBoxConstante = new javax.swing.JCheckBox();
        jLabelConstante = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jSpinnerIngreso = new javax.swing.JSpinner();
        jLabelConcepto = new javax.swing.JLabel();
        jTextFieldConcepto = new javax.swing.JTextField();
        jPanelErrorConcepto = new javax.swing.JPanel();
        jLabelCategoria = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonAnyadir = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelGastosFlexiblesTitulo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage((new ImageIcon(Login.class.getResource("/Imagenes/Icon.png"))).getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelGasto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelGasto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUnidadFamiliar.setText("Unidad Familiar");
        jPanelGasto.add(jLabelUnidadFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        jPanelGasto.add(jCheckBoxUnidadFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));
        jPanelGasto.add(jCheckBoxConstante, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabelConstante.setText("Regular");
        jPanelGasto.add(jLabelConstante, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabelCantidad.setText("Cantidad");
        jPanelGasto.add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jSpinnerIngreso.setModel(new javax.swing.SpinnerNumberModel(0.01d, 0.01d, 99999.99d, 1.0d));
        jPanelGasto.add(jSpinnerIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 113, -1));

        jLabelConcepto.setText("Concepto *");
        jPanelGasto.add(jLabelConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 28, -1, -1));
        jPanelGasto.add(jTextFieldConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 230, 27));

        jPanelErrorConcepto.setBackground(new java.awt.Color(255, 102, 102));
        jPanelErrorConcepto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelGasto.add(jPanelErrorConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 230, 27));

        jLabelCategoria.setText("Categoria");
        jPanelGasto.add(jLabelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Utilidades", "Cuentas", "Otros" }));
        jPanelGasto.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 148, -1, -1));

        getContentPane().add(jPanelGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 350, 180));

        jButtonAnyadir.setText("Añadir");
        jButtonAnyadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnyadirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnyadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 110, -1));

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 110, -1));

        jLabelGastosFlexiblesTitulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabelGastosFlexiblesTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGastosFlexiblesTitulo.setText("AÑADIR GASTO");
        getContentPane().add(jLabelGastosFlexiblesTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 350, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMorado.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 391, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Botón que se encarga de añadir un gasto
    private void jButtonAnyadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnyadirActionPerformed
        //Se comprueba que el concepto no esté vacío, en caso de serlo muestra el panel de error
        if (!jTextFieldConcepto.getText().isEmpty()) {
            if (!(jTextFieldConcepto.getText().toLowerCase().replaceAll("\\s", "")).equals("ahorro")) {
                try {
                    //Intenta insertar el gasto, si va todo correctamente avisa el usuario y lo añade a la tabla
                    Login.CONTROLADOR.insertarGastoIngreso(Login.USUARIO, jTextFieldConcepto.getText(), Double.valueOf(jSpinnerIngreso.getValue().toString()), jCheckBoxConstante.isSelected(), false, jCheckBoxUnidadFamiliar.isSelected(), jComboBox1.getSelectedItem().toString().toLowerCase());
                    switch (jComboBox1.getSelectedIndex()) {
                        case 0:
                            GastosFrame.modelUtilidades.addRow(new Object[]{jTextFieldConcepto.getText(), Double.valueOf(jSpinnerIngreso.getValue().toString()), jCheckBoxConstante.isSelected(), jCheckBoxUnidadFamiliar.isSelected()});
                            GastosFrame.anyadirUnGasto(Double.valueOf(new BigDecimal(Double.valueOf(jSpinnerIngreso.getValue().toString())).setScale(2, RoundingMode.HALF_DOWN).toString()));
                            break;
                        case 1:
                            GastosFrame.modelCuentas.addRow(new Object[]{jTextFieldConcepto.getText(), (Double) jSpinnerIngreso.getValue(), jCheckBoxConstante.isSelected(), jCheckBoxUnidadFamiliar.isSelected()});
                            GastosFrame.anyadirUnGasto(Double.valueOf(new BigDecimal(Double.valueOf(jSpinnerIngreso.getValue().toString())).setScale(2, RoundingMode.HALF_DOWN).toString()));
                            break;
                        case 2:
                            GastosFrame.modelOtros.addRow(new Object[]{jTextFieldConcepto.getText(), Double.valueOf(jSpinnerIngreso.getValue().toString()), jCheckBoxConstante.isSelected(), jCheckBoxUnidadFamiliar.isSelected()});
                            GastosFrame.anyadirUnGasto(Double.valueOf(new BigDecimal(Double.valueOf(jSpinnerIngreso.getValue().toString())).setScale(2, RoundingMode.HALF_DOWN).toString()));
                            break;
                    }
                    jCheckBoxUnidadFamiliar.setSelected(false);
                    jComboBox1.setSelectedIndex(0);
                    jCheckBoxConstante.setSelected(false);
                    jSpinnerIngreso.setValue(0);
                    jTextFieldConcepto.setText("");
                } catch (SQLException ex) {
                    //En caso de que el concepto ya exista en el mismo periodo avisa al usuario
                    JOptionPane.showMessageDialog(this, "Ya existe un ingreso/gasto con ese nombre", "Gasto no creado", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Para establecer el concepto de ahorro use su respectiva función en Gastos.", "Gasto no creado", JOptionPane.WARNING_MESSAGE);
            }

        } else {
            jPanelErrorConcepto.setVisible(true);
        }
    }//GEN-LAST:event_jButtonAnyadirActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnyadir;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JCheckBox jCheckBoxConstante;
    private javax.swing.JCheckBox jCheckBoxUnidadFamiliar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelConcepto;
    private javax.swing.JLabel jLabelConstante;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelGastosFlexiblesTitulo;
    private javax.swing.JLabel jLabelUnidadFamiliar;
    private javax.swing.JPanel jPanelErrorConcepto;
    private javax.swing.JPanel jPanelGasto;
    private javax.swing.JSpinner jSpinnerIngreso;
    private javax.swing.JTextField jTextFieldConcepto;
    // End of variables declaration//GEN-END:variables
}
