/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import java.awt.Color;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Date;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ángel Torada
 */
public class CompraGrande extends javax.swing.JFrame {

    /**
     * Constructor CompraGrande
     */
    public CompraGrande() {
        initComponents();

        //Oculto el panel de error
        jPanelErrorNombre.setVisible(false);

        //Cargo todos los valores
        cargarValores();

        //Establece la aparición de la ventana de manera centrada
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVolver = new javax.swing.JButton();
        jPanelBotones = new javax.swing.JPanel();
        jLabelGastoTotalMesTitulo = new javax.swing.JLabel();
        jLabelGastoTotalMes = new javax.swing.JLabel();
        jLabelNombreTitulo = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelCosteTitulo = new javax.swing.JLabel();
        jSpinnerCoste = new javax.swing.JSpinner();
        jLabelPeriodoDeCompraTitulo = new javax.swing.JLabel();
        jSpinnerMesPeriodoDeCompra = new javax.swing.JSpinner();
        jSpinnerAnyoPeriodoDeCompra = new javax.swing.JSpinner();
        jLabelMesTitulo = new javax.swing.JLabel();
        jLabelAnyoTitulo = new javax.swing.JLabel();
        jButtonCrearCompraGrande = new javax.swing.JButton();
        jPanelErrorNombre = new javax.swing.JPanel();
        jButtonEliminarCompraGrande = new javax.swing.JButton();
        jLabelGastosFlexiblesTitulo = new javax.swing.JLabel();
        jButtonCerrarSesion = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage((new ImageIcon(Login.class.getResource("/Imagenes/Icon.png"))).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, -1));

        jPanelBotones.setBackground(new java.awt.Color(249, 246, 248));
        jPanelBotones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelGastoTotalMesTitulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabelGastoTotalMesTitulo.setText("Gasto total por mes:");
        jPanelBotones.add(jLabelGastoTotalMesTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabelGastoTotalMes.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabelGastoTotalMes.setText("$");
        jPanelBotones.add(jLabelGastoTotalMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        jLabelNombreTitulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabelNombreTitulo.setText("Nombre *");
        jPanelBotones.add(jLabelNombreTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));
        jPanelBotones.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 50, 220, -1));

        jLabelCosteTitulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabelCosteTitulo.setText("Coste");
        jPanelBotones.add(jLabelCosteTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jSpinnerCoste.setModel(new javax.swing.SpinnerNumberModel(0.01d, 0.01d, 5.0E8d, 1.0d));
        jPanelBotones.add(jSpinnerCoste, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 132, -1));

        jLabelPeriodoDeCompraTitulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabelPeriodoDeCompraTitulo.setText("Periodo de compra");
        jPanelBotones.add(jLabelPeriodoDeCompraTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 132, -1));

        jSpinnerMesPeriodoDeCompra.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        jPanelBotones.add(jSpinnerMesPeriodoDeCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 80, -1));

        jSpinnerAnyoPeriodoDeCompra.setModel(new javax.swing.SpinnerNumberModel(2022, 2022, 2100, 1));
        jPanelBotones.add(jSpinnerAnyoPeriodoDeCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 82, -1));

        jLabelMesTitulo.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jLabelMesTitulo.setText("Mes");
        jPanelBotones.add(jLabelMesTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabelAnyoTitulo.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jLabelAnyoTitulo.setText("Año");
        jPanelBotones.add(jLabelAnyoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        jButtonCrearCompraGrande.setText("Crear Compra Grande");
        jButtonCrearCompraGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearCompraGrandeActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonCrearCompraGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jPanelErrorNombre.setBackground(new java.awt.Color(255, 102, 102));
        jPanelErrorNombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelBotones.add(jPanelErrorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 224, 28));

        jButtonEliminarCompraGrande.setText("Eliminar Compra Grande");
        jButtonEliminarCompraGrande.setEnabled(false);
        jButtonEliminarCompraGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarCompraGrandeActionPerformed(evt);
            }
        });
        jPanelBotones.add(jButtonEliminarCompraGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        getContentPane().add(jPanelBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 480, 310));

        jLabelGastosFlexiblesTitulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabelGastosFlexiblesTitulo.setText("COMPRA GRANDE");
        getContentPane().add(jLabelGastosFlexiblesTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jButtonCerrarSesion.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jButtonCerrarSesion.setText("Cerrar Sesión");
        jButtonCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCerrarSesionMouseExited(evt);
            }
        });
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 130, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMorado.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Botón que se encarga de volver a la pantalla anterior
    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        Main.INSTANCE.setVisible(true);
        Main.INSTANCE.establecerGastosEIngresos();
        this.dispose();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    //Botón que se encarga de cerrar la sesión
    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        Main.INSTANCE.dispose();
        Login.INSTANCE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    //Botón que se encarga de crear/modificar una compra grande
    private void jButtonCrearCompraGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearCompraGrandeActionPerformed
        //En caso de que el nombre no esté vacío la añade, si está vacío muestra el panel de error
        if (!jTextFieldNombre.getText().isEmpty()) {
            //Obtiene el periodo introducido por el usuario
            Date periodo = Date.valueOf(jSpinnerAnyoPeriodoDeCompra.getValue() + "-" + jSpinnerMesPeriodoDeCompra.getValue() + "-1");
            //Si el mes introducido es superior al actual entonces continua
            if (((int) jSpinnerMesPeriodoDeCompra.getValue() > LocalDate.now().getMonthValue()) && ((int) jSpinnerAnyoPeriodoDeCompra.getValue() == LocalDate.now().getYear())
                    || (LocalDate.now().getYear() < (int) jSpinnerAnyoPeriodoDeCompra.getValue())) {
                //Si el usuario no tenía una compra grande la crea
                if (jButtonCrearCompraGrande.getText().equals("Crear Compra Grande")) {
                    try {
                        Login.CONTROLADOR.insertarCompraGrande(Login.USUARIO, jTextFieldNombre.getText(), periodo, (double) jSpinnerCoste.getValue());
                        JOptionPane.showMessageDialog(this, "La compra grande ha sido creada.", "Compra grande creada", JOptionPane.INFORMATION_MESSAGE);
                        jPanelErrorNombre.setVisible(false);
                        cargarValores();
                    } catch (SQLException ex) {
                        Logger.getLogger(CompraGrande.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    //En caso de que ya tenga una compra grande la modifica
                    try {
                        Login.CONTROLADOR.actualizarCompraGrande(Login.USUARIO, jTextFieldNombre.getText(), periodo, (double) jSpinnerCoste.getValue());
                        JOptionPane.showMessageDialog(this, "La compra grande ha sido modificada.", "Compra grande modificada", JOptionPane.INFORMATION_MESSAGE);
                        cargarValores();
                    } catch (SQLException ex) {
                        System.out.println("Algo no ha salido bien con la conexión de la base de datos.");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "La compra grande tiene que ser en un mes posterior al actual.", "Compra grande no creada", JOptionPane.WARNING_MESSAGE);
            }

        } else {
            jPanelErrorNombre.setVisible(true);
        }
    }//GEN-LAST:event_jButtonCrearCompraGrandeActionPerformed

    //Listeners que se encargan de cambiar el color on Hover
    private void jButtonCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionMouseEntered
        jButtonCerrarSesion.setBackground(new Color(255, 102, 102));
        jButtonCerrarSesion.setForeground(Color.white);
    }//GEN-LAST:event_jButtonCerrarSesionMouseEntered

    private void jButtonCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionMouseExited
        jButtonCerrarSesion.setBackground(Color.white);
        jButtonCerrarSesion.setForeground(Color.black);
    }//GEN-LAST:event_jButtonCerrarSesionMouseExited

    //Botón que se encarga de eliminar una compra grande
    private void jButtonEliminarCompraGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarCompraGrandeActionPerformed
        try {
            Login.CONTROLADOR.deleteCompraGrande(Login.USUARIO);
            jButtonEliminarCompraGrande.setEnabled(false);
            JOptionPane.showMessageDialog(this, "La compra grande ha sido eliminada.", "Compra grande eliminada", JOptionPane.INFORMATION_MESSAGE);
            cargarValores();
        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_jButtonEliminarCompraGrandeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonCrearCompraGrande;
    private javax.swing.JButton jButtonEliminarCompraGrande;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelAnyoTitulo;
    private javax.swing.JLabel jLabelCosteTitulo;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelGastoTotalMes;
    private javax.swing.JLabel jLabelGastoTotalMesTitulo;
    private javax.swing.JLabel jLabelGastosFlexiblesTitulo;
    private javax.swing.JLabel jLabelMesTitulo;
    private javax.swing.JLabel jLabelNombreTitulo;
    private javax.swing.JLabel jLabelPeriodoDeCompraTitulo;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelErrorNombre;
    private javax.swing.JSpinner jSpinnerAnyoPeriodoDeCompra;
    private javax.swing.JSpinner jSpinnerCoste;
    private javax.swing.JSpinner jSpinnerMesPeriodoDeCompra;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables

    //Método que se encarga de rellenar los valores, en caso de que tenga o no una compra grande
    private void cargarValores() {
        //Obtiene la compra grande del usuario, si es nula entonces pone todo por defecto, sino carga sus datos
        ArrayList compraGrande = Login.CONTROLADOR.obtenerCompraGrandeUsuario(Login.USUARIO);
        if (!compraGrande.isEmpty()) {
            if ((((Date) compraGrande.get(1)).toLocalDate().getYear() - LocalDate.now().getYear()) >= 0) {
                jTextFieldNombre.setText(String.valueOf(compraGrande.get(0)));
                jSpinnerCoste.setValue(compraGrande.get(2));
                jSpinnerMesPeriodoDeCompra.setValue(((Date) compraGrande.get(1)).toLocalDate().getMonthValue());
                jSpinnerAnyoPeriodoDeCompra.setValue(((Date) compraGrande.get(1)).toLocalDate().getYear());
                jButtonCrearCompraGrande.setText("Modificar compra grande");
                jButtonEliminarCompraGrande.setEnabled(true);

                int mesesRestantes = (int) ChronoUnit.MONTHS.between(Login.CONTROLADOR.obtenerPeriodoActual().toLocalDate(), ((Date) compraGrande.get(1)).toLocalDate());

                try {
                    jLabelGastoTotalMes.setText(String.valueOf(new BigDecimal(((double) compraGrande.get(2)) / mesesRestantes).setScale(2, RoundingMode.HALF_DOWN)));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "La fecha de tu dispositivo está alterada, revísala.", "Error", JOptionPane.ERROR_MESSAGE);
                    this.dispose();
                    Main.INSTANCE.setVisible(true);
                }

            }
        } else {
            jButtonCrearCompraGrande.setText("Crear Compra Grande");
            jTextFieldNombre.setText("");
            jSpinnerCoste.setValue(0.01);
            jSpinnerMesPeriodoDeCompra.setValue(LocalDate.now().getMonthValue() + 1);
            jSpinnerAnyoPeriodoDeCompra.setValue(LocalDate.now().getYear());
            jLabelGastoTotalMes.setText("0");
        }
    }
}
