/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import Controlador.Controlador;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Ángel Torada
 */
public class Login extends javax.swing.JFrame {

    /**
     * Variable Controlador que permite el uso del mismo controlador a todas las
     * clases
     */
    static public Controlador CONTROLADOR;

    /**
     * Variable Usuario que se permite acceder al nombre del usuario que ha
     * iniciado sesión
     */
    static public String USUARIO;

    /**
     * Variable Instance que permite el acceso a la instancia princial del frame
     * login
     */
    static public Login INSTANCE;

    /**
     * Constructor del Frame Login
     */
    public Login() {
        initComponents();

        //Establece la posición al centro de la pantalla
        setLocationRelativeTo(null);

        //Instancia el controlador
        CONTROLADOR = new Controlador();

        //Instancia el atributo de la instancia del Login
        INSTANCE = this;

        //Oculta los paneles de error
        jPanelErrorUsuario.setVisible(false);
        jPanelErrorContrasenya.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLogo = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContrasenya = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonIniciar = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPanelErrorUsuario = new javax.swing.JPanel();
        jPanelErrorContrasenya = new javax.swing.JPanel();
        jLabelError = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage((new ImageIcon(Login.class.getResource("/Imagenes/Icon.png"))).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 20, 420, 120));

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabelUsuario.setText("Contraseña");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabelContrasenya.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabelContrasenya.setText("Usuario");
        getContentPane().add(jLabelContrasenya, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jTextFieldUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 210, -1));

        jButtonRegistrar.setBackground(new java.awt.Color(253, 243, 255));
        jButtonRegistrar.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jButtonRegistrar.setText("Registrarse");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        jButtonRegistrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonRegistrarKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 400, -1, -1));

        jButtonIniciar.setBackground(new java.awt.Color(253, 243, 255));
        jButtonIniciar.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });
        jButtonIniciar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonIniciarKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 310, -1, -1));

        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 210, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel1.setText("¿No tienes cuenta? ¡Regístrate!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 370, -1, -1));

        jPanelErrorUsuario.setBackground(new java.awt.Color(255, 102, 102));
        getContentPane().add(jPanelErrorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 199, 214, 30));

        jPanelErrorContrasenya.setBackground(new java.awt.Color(255, 102, 102));
        getContentPane().add(jPanelErrorContrasenya, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 269, 214, 30));

        jLabelError.setBackground(new java.awt.Color(255, 255, 255));
        jLabelError.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(242, 69, 69));
        getContentPane().add(jLabelError, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 350, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMorado.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 391, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Botón que abre el frame de registro
    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        registro();
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    //Botón que intenta iniciar sesión
    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        login();
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    //Listeners que escuchan el enter del usuario para iniciar sesión de manera rápida
    private void jTextFieldUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_jTextFieldUsuarioKeyPressed

    private void jPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_jPasswordFieldKeyPressed

    private void jButtonIniciarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonIniciarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_jButtonIniciarKeyPressed

    private void jButtonRegistrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonRegistrarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            registro();
        }
    }//GEN-LAST:event_jButtonRegistrarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    //Método que se encarga de abrir un frame de Registro
    private void registro() {
        Registro ventanaRegistro = new Registro();
        ventanaRegistro.setVisible(true);
        this.setVisible(false);
        jPanelErrorUsuario.setVisible(false);
        jPanelErrorContrasenya.setVisible(false);
        jLabelError.setText("");
    }

    //Método que intenta iniciar sesión y abre la vista principal
    private void login() {
        if (CONTROLADOR.iniciarSesion(jTextFieldUsuario.getText().toLowerCase(), jPasswordField.getText())) {
            USUARIO = jTextFieldUsuario.getText().toLowerCase();
            Main ventanaMain = new Main();
            ventanaMain.setVisible(true);
            this.setVisible(false);
            jPanelErrorUsuario.setVisible(false);
            jPanelErrorContrasenya.setVisible(false);
            jLabelError.setText("");
        } else {
            jPanelErrorUsuario.setVisible(true);
            jPanelErrorContrasenya.setVisible(true);
            jLabelError.setText("El usuario o la contraseña no son correctos");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelContrasenya;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelErrorContrasenya;
    private javax.swing.JPanel jPanelErrorUsuario;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
