/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import java.awt.Color;
import java.awt.Graphics;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Date;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ángel Torada
 */
public final class Main extends javax.swing.JFrame {

    /**
     * Variable Instance que permite el acceso a la instancia del panel princial
     * a todos los frames
     */
    static Main INSTANCE;

    /**
     * Constructor del Frame main
     */
    public Main() {
        initComponents();

        //Instancia el atributo Instance
        INSTANCE = this;

        comprobarCambioMes();

        //Carga todos los valores de los ingresos y los gastos
        establecerGastosEIngresos();

        //Crea el gráfico
        repaint();

        //Centra la ventana en la pantalla
        setLocationRelativeTo(null);

        //Establece el mensaje de bienvenido del usuario
        jLabelUsuario.setText("¡Bienvenido " + Login.USUARIO + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonIngresos = new javax.swing.JButton();
        jButtonGastos = new javax.swing.JButton();
        jButtonCompraGrande = new javax.swing.JButton();
        jButtonUnidadFamiliar = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jPanelGastosFlexibles = new javax.swing.JPanel();
        jLabelDineroDiario = new javax.swing.JLabel();
        jLabelMensualTitulo = new javax.swing.JLabel();
        jLabelSemanalTitulo = new javax.swing.JLabel();
        jLabelDineroMensual = new javax.swing.JLabel();
        jLabelDiarioTitulo = new javax.swing.JLabel();
        jLabelDineroSemanal = new javax.swing.JLabel();
        jButtonCerrarSesion = new javax.swing.JButton();
        jPanelResumen = new javax.swing.JPanel();
        jLabelProximaCompraGrande = new javax.swing.JLabel();
        jLabelProximaCompraTitulo = new javax.swing.JLabel();
        jLabelGastos = new javax.swing.JLabel();
        jLabelGastosTitulo = new javax.swing.JLabel();
        jLabelIngresosTitulo = new javax.swing.JLabel();
        jLabelIngresos = new javax.swing.JLabel();
        jLabelGastosFlexiblesTitulo = new javax.swing.JLabel();
        jLabelGastosFlexiblesTitulo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButtonUnidadFamiliar1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Finanzas");
        setIconImage((new ImageIcon(Login.class.getResource("/Imagenes/Icon.png"))).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonIngresos.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jButtonIngresos.setText("Gestionar Ingresos");
        jButtonIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 26));

        jButtonGastos.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jButtonGastos.setText("Gestionar Gastos");
        jButtonGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGastosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 190, 26));

        jButtonCompraGrande.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jButtonCompraGrande.setText("Gestionar Compra Grande");
        jButtonCompraGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompraGrandeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCompraGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 190, 26));

        jButtonUnidadFamiliar.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jButtonUnidadFamiliar.setText("Todos los movimientos");
        jButtonUnidadFamiliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnidadFamiliarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUnidadFamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 190, 26));

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsuario.setText("Usuario");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 220, 20));

        jPanelGastosFlexibles.setBackground(new java.awt.Color(255, 255, 255));
        jPanelGastosFlexibles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelGastosFlexibles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDineroDiario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDineroDiario.setText("$");
        jPanelGastosFlexibles.add(jLabelDineroDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 60, -1));

        jLabelMensualTitulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabelMensualTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMensualTitulo.setText("Mensual");
        jPanelGastosFlexibles.add(jLabelMensualTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 60, -1));

        jLabelSemanalTitulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabelSemanalTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSemanalTitulo.setText("Semanal");
        jPanelGastosFlexibles.add(jLabelSemanalTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 60, -1));

        jLabelDineroMensual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDineroMensual.setText("$");
        jPanelGastosFlexibles.add(jLabelDineroMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, -1));

        jLabelDiarioTitulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabelDiarioTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDiarioTitulo.setText("Diario");
        jPanelGastosFlexibles.add(jLabelDiarioTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 60, -1));

        jLabelDineroSemanal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDineroSemanal.setText("$");
        jPanelGastosFlexibles.add(jLabelDineroSemanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, -1));

        getContentPane().add(jPanelGastosFlexibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 250, 120, 160));

        jButtonCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCerrarSesion.setText("Cerrar Sesión");
        jButtonCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCerrarSesionMouseExited(evt);
            }
        });
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 120, -1));

        jPanelResumen.setBackground(new java.awt.Color(255, 255, 255));
        jPanelResumen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelProximaCompraGrande.setText("$");

        jLabelProximaCompraTitulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabelProximaCompraTitulo.setText("PRÓXIMA COMPRA GRANDE: ");

        jLabelGastos.setText("$");

        jLabelGastosTitulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabelGastosTitulo.setText("GASTOS DEL MES:");

        jLabelIngresosTitulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabelIngresosTitulo.setText("INGRESOS DEL MES:");

        jLabelIngresos.setText("$");

        javax.swing.GroupLayout jPanelResumenLayout = new javax.swing.GroupLayout(jPanelResumen);
        jPanelResumen.setLayout(jPanelResumenLayout);
        jPanelResumenLayout.setHorizontalGroup(
            jPanelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResumenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelProximaCompraTitulo)
                    .addComponent(jLabelProximaCompraGrande)
                    .addComponent(jLabelGastos)
                    .addComponent(jLabelGastosTitulo)
                    .addComponent(jLabelIngresos)
                    .addComponent(jLabelIngresosTitulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelResumenLayout.setVerticalGroup(
            jPanelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResumenLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelIngresosTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelIngresos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelGastosTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGastos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelProximaCompraTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelProximaCompraGrande)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 180, 160));

        jLabelGastosFlexiblesTitulo.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabelGastosFlexiblesTitulo.setText("RESUMEN");
        getContentPane().add(jLabelGastosFlexiblesTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, 40));

        jLabelGastosFlexiblesTitulo1.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabelGastosFlexiblesTitulo1.setText("GASTOS FLEXIBLES");
        getContentPane().add(jLabelGastosFlexiblesTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, -1, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel1.setText("Gastos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel2.setText("Ingresos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel3.setText("Gastos Flexibles");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jPanel2.setBackground(new java.awt.Color(253, 225, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 16));

        jPanel3.setBackground(new java.awt.Color(204, 169, 221));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, 16));

        jPanel4.setBackground(new java.awt.Color(242, 200, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, 16));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 350, 140));

        jButtonUnidadFamiliar1.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jButtonUnidadFamiliar1.setText("Unidad Familiar");
        jButtonUnidadFamiliar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnidadFamiliar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUnidadFamiliar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, 26));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMoradoGrande.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 710, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Botón que se encarga de abrir el frame de la unidad familiar
    private void jButtonUnidadFamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnidadFamiliarActionPerformed
        ListarFinanzas listarFinanzas = new ListarFinanzas(this, true);
        listarFinanzas.setVisible(true);
    }//GEN-LAST:event_jButtonUnidadFamiliarActionPerformed

    //Botón que se encarga de abrir el frame de los ingresos
    private void jButtonIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresosActionPerformed
        Ingresos ventanaIngresos = new Ingresos();
        ventanaIngresos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonIngresosActionPerformed

    //Botón que se encarga de abrir el frame de los gastos
    private void jButtonGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGastosActionPerformed
        Gastos ventanaGastos = new Gastos();
        ventanaGastos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonGastosActionPerformed

    //Botón que se encarga de abrir el frame de la compra grande
    private void jButtonCompraGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompraGrandeActionPerformed
        CompraGrande ventanaCompraGrande = new CompraGrande();
        ventanaCompraGrande.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCompraGrandeActionPerformed

    //Botón que se encarga de cerrar sesión
    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        Login.INSTANCE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    //Listeners que cambian el estilo del botón de cerrar sesión on Hover
    private void jButtonCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionMouseEntered
        jButtonCerrarSesion.setBackground(new Color(255, 102, 102));
        jButtonCerrarSesion.setForeground(Color.white);
    }//GEN-LAST:event_jButtonCerrarSesionMouseEntered

    private void jButtonCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionMouseExited
        jButtonCerrarSesion.setBackground(Color.white);
        jButtonCerrarSesion.setForeground(Color.black);
    }//GEN-LAST:event_jButtonCerrarSesionMouseExited

    private void jButtonUnidadFamiliar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnidadFamiliar1ActionPerformed
        UnidadFamiliar unidadFamiliar = new UnidadFamiliar();
        this.setVisible(false);
        unidadFamiliar.setVisible(true);
    }//GEN-LAST:event_jButtonUnidadFamiliar1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonCompraGrande;
    private javax.swing.JButton jButtonGastos;
    private javax.swing.JButton jButtonIngresos;
    private javax.swing.JButton jButtonUnidadFamiliar;
    private javax.swing.JButton jButtonUnidadFamiliar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDiarioTitulo;
    private javax.swing.JLabel jLabelDineroDiario;
    private javax.swing.JLabel jLabelDineroMensual;
    private javax.swing.JLabel jLabelDineroSemanal;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelGastos;
    private javax.swing.JLabel jLabelGastosFlexiblesTitulo;
    private javax.swing.JLabel jLabelGastosFlexiblesTitulo1;
    private javax.swing.JLabel jLabelGastosTitulo;
    private javax.swing.JLabel jLabelIngresos;
    private javax.swing.JLabel jLabelIngresosTitulo;
    private javax.swing.JLabel jLabelMensualTitulo;
    private javax.swing.JLabel jLabelProximaCompraGrande;
    private javax.swing.JLabel jLabelProximaCompraTitulo;
    private javax.swing.JLabel jLabelSemanalTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelGastosFlexibles;
    private javax.swing.JPanel jPanelResumen;
    // End of variables declaration//GEN-END:variables

    /**
     * Método que establece todos los valores de los ingresos y gastos del panel
     * principal
     */
    protected void establecerGastosEIngresos() {
        //Obtiene todos los gastos e ingresos del usuario
        HashMap ingresos = Login.CONTROLADOR.obtenerIngresosUsuario(Login.USUARIO, null);
        HashMap gastos = Login.CONTROLADOR.obtenerGastosUsuario(Login.USUARIO, null);

        //Obtiene y establece el sumatorio de todos los ingresos
        double ingresosTotales = 0;
        for (Object entry : ingresos.entrySet()) {
            ingresosTotales += (Double) ((Map.Entry<String, ArrayList>) entry).getValue().get(0);
        }

        jLabelIngresos.setText(String.valueOf(new BigDecimal(ingresosTotales).setScale(2, RoundingMode.HALF_DOWN)));

        //Obtiene el sumatorio de todos los gastos
        double gastosTotales = 0;

        for (Object entry : gastos.entrySet()) {//System.out.println(((Map.Entry<String, Double>) entry).getKey() + "/" + ((Map.Entry<String, Double>) entry).getValue());
            gastosTotales += (Double) ((Map.Entry<String, ArrayList>) entry).getValue().get(0);
        }

        //Obtiene y establece la cantidad del mes actual de la compra grande
        ArrayList compraGrande = Login.CONTROLADOR.obtenerCompraGrandeUsuario(Login.USUARIO);

        if (!compraGrande.isEmpty()) {
            int mesesRestantes = (int) ChronoUnit.MONTHS.between(Login.CONTROLADOR.obtenerPeriodoActual().toLocalDate(), ((Date) compraGrande.get(1)).toLocalDate());

            try {
                jLabelProximaCompraGrande.setText(String.valueOf(new BigDecimal(((double) compraGrande.get(2)) / mesesRestantes).setScale(2, RoundingMode.HALF_DOWN)));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "La fecha de tu dispositivo está alterada, revísala.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            gastosTotales += Double.valueOf(jLabelProximaCompraGrande.getText());
        } else {
            jLabelProximaCompraGrande.setText("0");
        }

        //Establece los gastos totales
        jLabelGastos.setText(String.valueOf(new BigDecimal(gastosTotales).setScale(2, RoundingMode.HALF_DOWN).toString()));

        double gastosMensuales = ingresosTotales - gastosTotales;

        if (gastosMensuales < 0) {
            jLabelDineroMensual.setForeground(Color.red);
            jLabelDineroSemanal.setForeground(Color.red);
            jLabelDineroDiario.setForeground(Color.red);
        } else {
            jLabelDineroMensual.setForeground(Color.black);
            jLabelDineroSemanal.setForeground(Color.black);
            jLabelDineroDiario.setForeground(Color.black);
        }

        //Establece los gastos flexibles para el usuario
        jLabelDineroMensual.setText(String.valueOf(new BigDecimal((gastosMensuales)).setScale(2, RoundingMode.HALF_DOWN)));
        jLabelDineroSemanal.setText(String.valueOf(new BigDecimal((gastosMensuales / 4)).setScale(2, RoundingMode.HALF_DOWN)));
        if (LocalDate.now().getMonth().getValue() != 2) {
            jLabelDineroDiario.setText(String.valueOf(new BigDecimal((gastosMensuales / 31)).setScale(2, RoundingMode.HALF_DOWN)));
        } else {
            jLabelDineroDiario.setText(String.valueOf(new BigDecimal((gastosMensuales / 28)).setScale(2, RoundingMode.HALF_DOWN)));
        }

    }

    //Método paint que se encarga de crear el gráfico
    @Override
    public void paint(Graphics g) {
        super.paint(g);

        try {

            //Obtiene todos los valores de los gastos, ingresos y dinero flesible
            int gastos = (int) ((double) Double.valueOf(jLabelGastos.getText()));
            int ingresos = (int) ((double) Double.valueOf(jLabelIngresos.getText()));
            int flexibles = (int) ((double) Double.valueOf(jLabelDineroMensual.getText()));

            //Calcula canto % ocuparán en el círculo
            int total = gastos + ingresos + flexibles;
            int gradosGastos = gastos * 360 / total;
            int gradosIngresos = ingresos * 360 / total;
            int gradosFlexibles = flexibles * 360 / total;

            //Crea cada porción
            g.setColor(new Color(253, 225, 255));
            g.fillArc(490, 93, 115, 115, 0, gradosGastos);

            g.setColor(new Color(242, 200, 255));
            g.fillArc(490, 93, 115, 115, gradosGastos, gradosIngresos);

            g.setColor(new Color(204, 169, 221));
            g.fillArc(490, 93, 115, 115, gradosIngresos + gradosGastos, gradosFlexibles);
        } catch (Exception e) {
            //En caso de que sea un usuario nuevo se establecerá esto por defecto
            g.setColor(new Color(253, 225, 255));
            g.fillArc(490, 93, 115, 115, 0, 100 * 360 / 300);

            g.setColor(new Color(242, 200, 255));
            g.fillArc(490, 93, 115, 115, 100 * 360 / 300, 100 * 360 / 300);

            g.setColor(new Color(204, 169, 221));
            g.fillArc(490, 93, 115, 115, (100 * 360 / 300) * 2, 100 * 360 / 300);
        }

    }

    private void comprobarCambioMes() {
        Date ultimoInicio = Login.CONTROLADOR.ultimoInicioUsuario(Login.USUARIO);
        int mes = ultimoInicio.toLocalDate().getMonthValue();

        HashMap gastos;
        HashMap ingresos;

        LocalDate mesPasado = LocalDate.now();
        String periodo = mesPasado.getYear() + "-" + (mesPasado.getMonthValue() - 1) + "-1";

        if (mes != LocalDate.now().getMonthValue()) {

            gastos = Login.CONTROLADOR.obtenerGastosUsuario(Login.USUARIO, Date.valueOf(periodo));
            ingresos = Login.CONTROLADOR.obtenerIngresosUsuario(Login.USUARIO, Date.valueOf(periodo));
            System.out.println(gastos);
            System.out.println(ingresos);

            for (Object entry : ingresos.entrySet()) {
                ArrayList atributos = ((Map.Entry<String, ArrayList>) entry).getValue();
                if (Boolean.valueOf(atributos.get(1).toString())) {
                    try {
                        Login.CONTROLADOR.insertarGastoIngreso(Login.USUARIO, ((Map.Entry<String, ArrayList>) entry).getKey(), (double) atributos.get(0), true, true, (boolean) atributos.get(2), null);
                    } catch (SQLException ex) {
                    }
                }
            }

            for (Object entry : gastos.entrySet()) {
                ArrayList atributos = ((Map.Entry<String, ArrayList>) entry).getValue();
                if (Boolean.valueOf(atributos.get(2).toString())) {
                    try {
                        Login.CONTROLADOR.insertarGastoIngreso(Login.USUARIO, ((Map.Entry<String, ArrayList>) entry).getKey(), (double) atributos.get(0), true, false, (boolean) atributos.get(3), atributos.get(1).toString());
                    } catch (SQLException ex) {
                    }
                }
            }

        }

    }

}
